# Разрешение в точках на см нити
resolution: 100

# Диаметр нити в см
diameter: 0.2

# Длина ниток утка в см = ширина куска
width: 20

# Линейная плотность утка в нитях на см
weft_density: 1

# Длина ниток основы = длина куска
length: 50 # В см

# Линейная плотность основы в нитях на см
warp_density: 0.5
