# Конфиг представляет собой список задач (tasks)
# и директорию, для записи результатов (out_dir)
# Каждый task имеет вид
# name: simple # название таска, результат будет иметь вид: ${name}.vtu
#  resolution: 100 # Разрешение нитей, точек/см
#  diameter: 0.5 # толщина нити, см
#  width: 20 # Ширина куска = длина ниток утка
#  weft_density: 1 # Плотность ниток утка, нитей / см
#  length: 50 # Длина куска = длина ниток основы
#  warp_density: 0.5 # Плотность ниток основы, нитей / см

---
out_dir: out

tasks:
  - name: simple
    resolution: 100
    diameter: 0.5
    width: 20
    weft_density: 1
    length: 50
    warp_density: 0.5
