# Конфиг представляет собой список задач (tasks)
# и директорию, для записи результатов (out_dir)
# Каждый task имеет вид
# name: simple # название таска, результат будет иметь вид: ${name}.vtu
# mesh:
#   resolution: 100 # Разрешение нитей, точек/см
#   diameter: 0.5 # толщина нити, см
#   width: 20 # Ширина куска = длина ниток утка
#   weft_density: 1 # Плотность ниток утка, нитей / см
#   length: 50 # Длина куска = длина ниток основы
#   warp_density: 0.5 # Плотность ниток основы, нитей / см
# solver:
#    n_steps: 250 # Число шагов
#    step: 0.1 # размер шага
#    pulse:
#       radius: 5 # Радиус нагрузки
#       amplitude: 1 # Амплитуда нагрузки
#       center: # Точка нагрузки
#          x: 50
#          y: 50
#          z: 0
#
# NOTE: Конфиг поддерживает шаблоны jinja2
---
out_dir: out

tasks:
  - name: simple
    mesh:
      resolution: 1
      diameter: 0.001
      width: 100
      weft_density: 1
      length: 100
      warp_density: 1
    solver:
      step: 0.1
      n_steps: 1000
      pulse:
        radius: 5
        amplitude: 1
        center:
          x: 50
          y: 50
          z: 0
{#  {% for step in [0.1, 0.05, 0.02] %}#}
{#  - name: "step-{{ step }}"#}
{#    mesh:#}
{#      resolution: 1#}
{#      diameter: 0.001#}
{#      width: 100#}
{#      weft_density: 1#}
{#      length: 100#}
{#      warp_density: 1#}
{#    solver:#}
{#      step: !!float "{{ step }}"#}
{#      n_steps: !!int "{{ (25/step)|round|int }}"#}
{#      pulse:#}
{#        radius: 5#}
{#        amplitude: 1#}
{#        center:#}
{#          x: 50#}
{#          y: 50#}
{#          z: 0#}
{#  {% endfor %}#}
