# Разрешение в точках на см нити
resolution: 10
layer:
  # Длина ниток утка в см = ширина куска
  width: 50

  # Уток
  weft:
    # Линейная плотность в нитях на см
    density: 10

    # Диаметр нити в см
    diameter: 0.2

  # Длина ниток основы = длина куска
  length: 50 # В см

  # Основа
  warp:
    # Линейная плотность в нитях на см
    density: 5

    # Диаметр нити в см
    diameter: 0.2
