# Разрешение в точках на см нити
resolution: 10

# Диаметр нити в см
diameter: 0.2

# Длина ниток утка в см = ширина куска
width: 50

# Линейная плотность утка в нитях на см
weft_density: 2

# Длина ниток основы = длина куска
length: 50 # В см

# Линейная плотность основы в нитях на см
warp_density: 1
